{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin.fullname" . }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "admin.name" . }}
    app.kubernetes.io/component: admin
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "admin.name" . }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
