{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if ne .Values.service.type "ClusterIP" }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- else }}
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  {{- end }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}
