apiVersion: v2
name: web
description: YetAnotherBoilerplate web frontend Helm chart
# application chart
type: application
version: 0.1.0
appVersion: "0.0.0"
keywords:
  - web
  - frontend
  - flutter
home: https://github.com/jkobti/yetAnotherBoilerplate
sources:
  - https://github.com/jkobti/yetAnotherBoilerplate
maintainers:
  - name: jkobti
    url: https://github.com/jkobti
dependencies: []
