apiVersion: v2
name: observability
description: Observability stack (Prometheus, Grafana) for YetAnotherBoilerplate
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "66.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
  - name: loki-stack
    version: "2.10.2"
    repository: https://grafana.github.io/helm-charts
    condition: loki-stack.enabled
