{{- if and .Values.enabled .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
    {{- if .Values.prometheusRule.labels }}
    {{- toYaml .Values.prometheusRule.labels | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "api.fullname" . }}
      rules:
        {{- toYaml .Values.prometheusRule.rules | nindent 8 }}
{{- end }}
